### ISSUE TITLE
Improve react-ga tracking

### ISSUE THREAD

**Issue by mrozilla** [mrozilla/mrozilla.cz#9]
# resources
- https://philipwalton.com/articles/the-google-analytics-setup-i-use-on-every-site-i-build/

# todos
- [ ] track external clicks to blog
- [ ] track code version as custom dimension
- [ ] ? use navigator.sendBeacon
